// Danh sách ngôn ngữ
const languages = {
  en: 'English',
  vi: 'Vietnamese',
  es: 'Spanish',
  fr: 'French',
  de: 'German',
  ja: 'Japanese',
  zh: 'Chinese',
  ar: 'Arabic',
  pt: 'Portuguese',
  ru: 'Russian',
  it: 'Italian',
  ko: 'Korean',
  hi: 'Hindi',
  pl: 'Polish',
  tr: 'Turkish',
  nl: 'Dutch',
  sv: 'Swedish',
  da: 'Danish',
  fi: 'Finnish',
  no: 'Norwegian',
  el: 'Greek',
  cs: 'Czech',
  th: 'Thai',
  he: 'Hebrew',
  hu: 'Hungarian',
  ro: 'Romanian',
  sr: 'Serbian',
  uk: 'Ukrainian',
  id: 'Indonesian',
  ms: 'Malay',
  sw: 'Swahili',
  ta: 'Tamil',
  bn: 'Bengali',
  ur: 'Urdu',
  fa: 'Persian',
  mk: 'Macedonian',
  bg: 'Bulgarian',
  lv: 'Latvian',
  lt: 'Lithuanian',
  is: 'Icelandic',
  hr: 'Croatian',
  sl: 'Slovenian',
  et: 'Estonian',
  bs: 'Bosnian',
  am: 'Amharic',
  ml: 'Malayalam',
  te: 'Telugu',
  kn: 'Kannada',
  mr: 'Marathi',
  gu: 'Gujarati',
  pa: 'Punjabi',
  as: 'Assamese',
  si: 'Sinhala',
  km: 'Khmer',
  la: 'Latin',
  mn: 'Mongolian',
  my: 'Burmese',
  ne: 'Nepali',
  sq: 'Albanian',
  ht: 'Haitian Creole',
  sw: 'Swahili',
};

export default languages;